version: "3.8"
services:
  frontend:
        container_name: frontend_app
        image: frontend
        build:
          context: ./frontend/my-app
          target: staging
        ports:
          - 3000:3000