version: "3.8"
services:
  frontend:
        container_name: frontend_app
        image: frontend
        build:
          context: ./frontend/my-app
          target: dev
        ports:
          - 3000:3000
        depends_on:
          - backendone
          - backendtwo
        networks:
            - service-net
  backendone:
        container_name: service_one
        image: service-one
        build:
          context: ./service-one
          target: dev
        ports: 
          - 5001:5000
        networks:
            - service-net
  backendtwo:
        container_name: service_two
        image: service-two
        build:
          context: ./service-two
          target: dev
        
        ports: 
          - 5002:5000
        depends_on:
            - backendone
        networks:
            - service-net

networks:
    service-net:
      driver: bridge
          