version: "3.8"
services:
  frontend:
        container_name: frontend_app
        image: frontend
        build:
          context: ./frontend/my-app
          target: production
        ports:
          - 8000:80
        depends_on:
          - backendone
          - backendtwo
        networks:
          - service-net
  backendone:
        container_name: service_one
        image: service-one
        build:
          context: ./service-one
          target: production
        networks:
            - service-net
        ports: 
          - 5001:5000
  backendtwo:
        container_name: service_two
        image: service-two
        build:
          context: ./service-two
          target: production
        networks:
            - service-net
        ports: 
          - 5002:5000
        depends_on:
            - backendone

networks:
    service-net:
      driver: bridge
