site_name: Micro-Devops-Tutorial
theme:
  name: material
  features:
    - navigation.expand

nav:
    - Intro: 'index.md'
    - About Me: 'about.md'
    - 'Containerization':
        - 'Conatainer with Docker': 'docker-containerization.md'
        - 'Docker Compose In Action': 'docker-compose.md'
        - 'Docker Multi Staging': 'docker-multistage.md'
#    - 'Load Balancing':
#    - 'Linux Server':
#    - 'Ansible':
#    - 'ELK Stack':